export enum SearchContextAction {
  EXECUTE_SEARCH,
  SET_HISTORY,
  REMOVE_HISTORY_ITEM,
  RESET_SEARCH,
  SEARCH_SUCCESS_INFLIGHT,
  SEARCH_SUCCESS_COMPLETE,
  SEARCH_UNAUTHORIZED,
  SEARCH_ERROR,
}
