export enum ChatGptResultState {
  INITIAL,
  UNAUTHORIZED,
  LOADING,
  SUCCESS,
  ERROR,
}

export const KEY_ACCESS_TOKEN = "accessToken";

export const CHAT_GPT_HISTORY_KEY = "CHAT_GPT_HISTORY";
export const CHAT_GPT_SETTINGS_KEY = "CHAT_GPT_SETTINGS_KEY";
export enum ChatGptSettingsKey {
  ENABLE_CONTENT_SCRIPT = "ENABLE_CONTENT_SCRIPT",
  EAGER_SEARCH = "EAGER_SEARCH",
  IFRAME_POPUP = "IFRAME_POPUP",
  RETURN_STUB_MESSAGE = "RETURN_STUB_MESSAGE",
}

export enum MessageType {
  SEND_PROMPT = "SEND_PROMPT",
  SEND_PROMPT_RESPONSE = "SEND_PROMPT_RESPONSE",
}
